services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - EDITOR=vi
    tty: true
    stdin_open: true
    entrypoint: ./entrypoint.dev.sh
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
